
@startuml
participant API_Gateway as "API Gateway"
participant DeviceManagementAPI as "API Управления Устройствами"
participant CommandHandler as "Обработчик Команд"
participant DeviceStateManager as "Менеджер Состояния Устройств"
participant TelemetryManager as "Менеджер Телеметрии"
participant DeviceManagementDB as "БД Управления Устройствами"
participant TelemetryDB as "БД Телеметрии"
participant Kafka as "Кафка"

User -> API_Gateway : "POST /device/on"
API_Gateway -> DeviceManagementAPI : "Запрос управления устройствами"
DeviceManagementAPI -> CommandHandler : "Обработка команды"
CommandHandler -> DeviceStateManager : "Изменение состояния устройства"
DeviceStateManager -> DeviceManagementDB : "Обновление состояния устройства"
DeviceStateManager -> Kafka : "Публикация события изменения состояния"

User -> API_Gateway : "GET /telemetry"
API_Gateway -> TelemetryManager : "Запрос данных телеметрии"
TelemetryManager -> TelemetryDB : "Получение данных телеметрии"

@enduml
